
include: package:flutter_lints/flutter.yaml

formatter: 
  trailing_commas: preserve

analyzer:
  errors:
    todo: ignore
    missing_required_param: warning

linter:
  rules:
    always_declare_return_types: true
    avoid_print: false
    prefer_const_constructors: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    